// src/lib/Social.svelte
<script lang="ts">
  import LinkedInIcon from './Icons/LinkedIn.svelte';
  import StackOverflowIcon from './Icons/StackOverflow.svelte';
  import TwitterIcon from './Icons/Twitter.svelte';
  import ObservableIcon from './Icons/Observable.svelte';
  import GithubIcon from './Icons/Github.svelte';
</script>

<footer>
  <a href="https://github.com/kube" target="__blank">
    <GithubIcon class="icon" style="fill:#6e5494" />
  </a>
  <a href="https://linkedin.com/in/cfeijoo" target="__blank">
    <LinkedInIcon class="icon" style="fill:#0077b5" />
  </a>
  <a
    href="https://stackoverflow.com/users/1914206/kube?tab=profile"
    target="__blank"
  >
    <StackOverflowIcon class="icon" style="fill:#ff9900" />
  </a>
  <a href="https://twitter.com/KubeKhrm" target="__blank">
    <TwitterIcon class="icon" style="fill:#00aced" />
  </a>
</footer>

<style lang="scss">
  * :global(.icon) {
    margin: 7px;
    max-width: 31px;
    max-height: 31px;
    fill: var(--palette-dark-grey);
    transition: transform 0.3s;

    &:hover {
      transform: scale(1.15);
    }
    &:active {
      transform: scale(0.94);
      fill: var(--palette-purple);
    }
  }
</style>

// app/components/Social.tsx
import { cn } from "../utils";
import Collective from "./icons/Collective";
import GithubIcon from "./icons/Github";
import LinkedInIcon from "./icons/LinkedIn";
import MaltIcon from "./icons/Malt";
import StackOverflowIcon from "./icons/StackOverflow";
import TwitterIcon from "./icons/Twitter";

import React from "react";
import { Link } from "react-router";

const SocialLinkIcon: React.FC<{
  to: string;
  icon: (props: any) => React.ReactElement;
  className: string;
}> = ({ to, icon: Icon, className }) => (
  <Link to={to} target="_blank">
    <Icon
      className={cn(
        "h-10 w-10 hover:scale-105 transition-all active:scale-90 active:brightness-100 hover:brightness-90 dark:hover:brightness-150",
        className
      )}
    />
  </Link>
);

export const SocialLink: React.FC = () => (
  <footer className="flex gap-7">
    <SocialLinkIcon
      to="//github.com/kube"
      icon={GithubIcon}
      className="fill-[#6e5494]"
    />
    <SocialLinkIcon
      to="//www.malt.fr/profile/chrisfeijoo"
      icon={MaltIcon}
      className="fill-[#fc5757]"
    />
    <SocialLinkIcon
      to="//app.collective.work/collective/novae-preyt7of"
      icon={Collective}
      className="fill-[#adb6be]"
    />
    <SocialLinkIcon
      to="//linkedin.com/in/cfeijoo"
      icon={LinkedInIcon}
      className="fill-[#0077b5]"
    />
    <SocialLinkIcon
      to="//stackoverflow.com/users/1914206/kube"
      icon={StackOverflowIcon}
      className="fill-[#ff9900]"
    />
    <SocialLinkIcon
      to="//x.com/KubeKhrm"
      icon={TwitterIcon}
      className="fill-[#00aced]"
    />
  </footer>
);
